### ISSUE TITLE
how does one use it?

### ISSUE THREAD

**Issue by niedakh** [oandrew/ipod#1]
Hi,

having a raspberry pi setup, how do I use it? what kind of cable do I need for it?

**Comment by oandrew** [comment]
Hi,

You need to start here first:
https://github.com/oandrew/ipod-gadget

You will need a typical Micro-B to A cable

**Comment by ShinoNia** [comment]
> Hi,
> 
> You need to start here first: https://github.com/oandrew/ipod-gadget
> 
> You will need a typical Micro-B to A cable



Hi
Sorry if this is not the place to ask, I'm kinda clueless about this
My host device has the connector like this. Is it possible to connect to it easily or I need to do further tikering?

![image](https://github.com/oandrew/ipod/assets/97570575/1d78fe1f-3309-4089-8dbf-af4d20729cdc)
