### ISSUE TITLE
Go Build Error

### ISSUE THREAD

**Issue by camper8080** [oandrew/ipod#5]
Hi,

Hardware: Raspberry Pi Zero W
OS: Linux raspberrypi 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux
Golang Version: go version go1.11.6 linux/arm

I'm having an issue running the following command:

pi@raspberrypi:~ $ go get -v github.com/oandrew/ipod/cmd/ipod
github.com/oandrew/ipod (download)
github.com/davecgh/go-spew (download)
github.com/fullsailor/pkcs7 (download)
github.com/sirupsen/logrus (download)
Fetching https://golang.org/x/sys/unix?go-get=1
Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"}                                                                                     at https://golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
github.com/urfave/cli (download)
github.com/cpuguy83/go-md2man (download)
Fetching https://golang.org/x/crypto/ssh/terminal?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh/terminal?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh/terminal": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googleso                                                                                    urce.com/crypto"} at https://golang.org/x/crypto/ssh/terminal?go-get=1
get "golang.org/x/crypto/ssh/terminal": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
github.com/davecgh/go-spew/spew
github.com/fullsailor/pkcs7
github.com/oandrew/ipod
github.com/oandrew/ipod/hid
github.com/oandrew/ipod/lingo-audio
github.com/oandrew/ipod/lingo-dispremote
github.com/oandrew/ipod/lingo-extremote
github.com/oandrew/ipod/lingo-general
github.com/oandrew/ipod/lingo-simpleremote
github.com/oandrew/ipod/trace
golang.org/x/sys/unix
github.com/sirupsen/logrus
github.com/cpuguy83/go-md2man/vendor/github.com/shurcooL/sanitized_anchor_name
github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/v2
github.com/cpuguy83/go-md2man/md2man
github.com/urfave/cli
golang.org/x/crypto/ssh/terminal
github.com/oandrew/ipod/cmd/ipod
github.com/oandrew/ipod/cmd/ipod
go/src/github.com/oandrew/ipod/cmd/ipod/main.go:66:14: cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignme                                                                                    nt
go/src/github.com/oandrew/ipod/cmd/ipod/main.go:76:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slic                                                                                    e literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/oandrew/ipod/cmd/ipod/main.go:95:7: c.GlobalBool undefined (type *cli.Context has no field or method GlobalBool)
go/src/github.com/oandrew/ipod/cmd/ipod/main.go:102:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assi                                                                                    gnment
go/src/github.com/oandrew/ipod/cmd/ipod/main.go:118:19: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or                                                                                     slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/oandrew/ipod/cmd/ipod/main.go:205:19: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or                                                                                     slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)

Thank you in advance.

**Comment by oandrew** [comment]
@camper8080 

Should be fixed with the latest master. 
Also make sure to add `GO111MODULE=on` (see README)

**Comment by camper8080** [comment]
The latest master resolved the issue. Thanks for this project and your time.

**Comment by dzid26** [comment]
Just wanted to say that with go 1.11,  (which is currently a default when running `sudo apt-get install golang` on current RaspberryPi), the build command with `GO111MODULE`  [didn't work](https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k#-raw-go111module-endraw-with-go-111-and-112).

After installing 1.13 (following second part of [the guide](https://www.e-tinkers.com/2019/06/better-way-to-install-golang-go-on-raspberry-pi/)), it built successfully.
