### ISSUE TITLE
GetDevAuthenticationInfo

### ISSUE THREAD

**Issue by kanonochina** [oandrew/ipod#8]
Hi @oandrew, my build was stuck in iPod READING FILE then goes to iPod ERROR 5 on the headunit display.
Here is my trace file
https://gist.github.com/kanonochina/b7db99d1bababf549522d24178609f38

Thanks so much.

**Comment by oandrew** [comment]
hi @kanonochina, 

i've pushed some changes that might fix the issue for you.

**Comment by kanonochina** [comment]
Thanks @oandrew, I really appreciate the reply. 
the update sure get the logs fired up but still, the same "iPod ERROR 5" after a minute of displaying "iPod READING FILE",  I can hear the audio after I quickly turn the power off in the head unit then turn it on again while the head unit displays  "iPod READING FILE"

here is the last trace logs
https://gist.github.com/kanonochina/42d68b0c8d981f0082123659e3e4964f

Thanks again

**Comment by oandrew** [comment]
try with current master

**Comment by kanonochina** [comment]
Sorry, the same issue

I'm not sure if it would help but the car is a Subaru BRZ with a Fujitsu head unit

trace logs are here:
https://gist.github.com/kanonochina/bdd5f002bf6a090762e1408c13dad67a


![Photo on 06-03-2020 at 4 30 PM](https://user-images.githubusercontent.com/8895647/76066171-062e0a80-5fc8-11ea-9659-031722048711.jpg)
